import cloudflare from '@astrojs/cloudflare'
import { defineConfig } from 'astro/config'
import compress from 'astro-compress'
import htmlMinifierNext from 'astro-html-minifier-next'
import browserslist from 'browserslist'
import { browserslistToTargets } from 'lightningcss'

const lightningCssOptions = {
  minify: true,
  errorRecovery: false,
  targets: browserslistToTargets(browserslist('defaults')),
}

// https://astro.build/config
export default defineConfig({
  adapter: cloudflare({
    // we handle this with compress()
    imageService: 'passthrough',
  }),

  i18n: {
    locales: ['en', 'ja'],
    defaultLocale: 'en',
    routing: 'manual',
  },

  site: 'https://aly.fish',

  compressHTML: false,
  vite: {
    build: {
      cssMinify: 'lightningcss',
    },
    css: {
      lightningcss: lightningCssOptions,
    },
  },
  integrations: [
    htmlMinifierNext({
      alwaysWriteMinifiedHTML: true,
      caseSensitive: true,
      collapseBooleanAttributes: true,
      collapseInlineTagWhitespace: false,
      collapseWhitespace: true,
      conservativeCollapse: false,
      continueOnParseError: false,
      decodeEntities: true,
      html5: true,
      includeAutoGeneratedTags: true,
      keepClosingSlash: false,
      minifyCSS: lightningCssOptions,
      minifyJS: true,
      minifyURLs: false,
      noNewlinesBeforeTagClose: false,
      preserveLineBreaks: false,
      preventAttributesEscaping: false,
      processConditionalComments: false,
      removeAttributeQuotes: false,
      removeComments: true,
      removeEmptyAttributes: true,
      removeEmptyElements: false,
      removeOptionalTags: false,
      removeRedundantAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      removeTagWhitespace: false,
      sortAttributes: false,
      sortClassName: false,
      useShortDoctype: true,
    }),
    compress({
      HTML: false,
      CSS: {
        csso: false,
        lightningcss: lightningCssOptions,
      },
      Exclude: ['88x31.svg'],
    }),
  ],
})
