import * as fs from 'node:fs'
import cloudflare from '@astrojs/cloudflare'
import type { AstroIntegration } from 'astro'
import { defineConfig } from 'astro/config'
import compress from 'astro-compress'
import htmlMinifierNext from 'astro-html-minifier-next'
import browserslist from 'browserslist'
import { browserslistToTargets } from 'lightningcss'

const lightningCssOptions = {
  minify: true,
  errorRecovery: false,
  targets: browserslistToTargets(browserslist('defaults')),
}

const generateCloudflareRoutes: AstroIntegration = {
  name: 'generate-cloudflare-routes',
  hooks: {
    'astro:build:done': (result) => {
      const staticPages = result.pages.map((p) => `/${p.pathname}`)
      const staticAssets = []

      if (fs.existsSync('public')) {
        const publicFolder = fs.readdirSync('public', { withFileTypes: true })
        for (const publicChild of publicFolder) {
          if (publicChild.isDirectory()) {
            staticAssets.push(`/${publicChild.name}/*`)
          } else {
            staticAssets.push(`/${publicChild.name}`)
          }
        }
      }

      const runWorkerFirst = [
        '/*',
        ...staticPages.map((p) => `!${p}`),
        ...staticAssets.map((p) => `!${p}`),
      ]

      const wranglerJsonPath = new URL('../server/wrangler.json', result.dir)
      const existingWranglerText = fs.readFileSync(wranglerJsonPath).toString()
      const existingWrangler = JSON.parse(existingWranglerText)
      // biome-ignore lint/complexity/useLiteralKeys: it's not camelCase lol
      existingWrangler.assets['run_worker_first'] = runWorkerFirst
      const newWrangler = JSON.stringify(existingWrangler)
      fs.writeFileSync(wranglerJsonPath, newWrangler)
    },
  },
}

// https://astro.build/config
export default defineConfig({
  adapter: cloudflare({
    // we handle this with compress()
    imageService: 'passthrough',
    prerenderEnvironment: 'node',
  }),

  i18n: {
    locales: ['en', 'ja'],
    defaultLocale: 'en',
    routing: 'manual',
  },

  site: 'https://aly.fish',

  compressHTML: false,
  vite: {
    build: {
      cssMinify: 'lightningcss',
    },
    css: {
      lightningcss: lightningCssOptions,
    },
  },
  integrations: [
    htmlMinifierNext({
      alwaysWriteMinifiedHTML: true,
      caseSensitive: true,
      collapseBooleanAttributes: true,
      collapseInlineTagWhitespace: false,
      collapseWhitespace: true,
      conservativeCollapse: false,
      continueOnParseError: false,
      decodeEntities: true,
      includeAutoGeneratedTags: true,
      keepClosingSlash: false,
      minifyCSS: lightningCssOptions,
      minifyJS: true,
      minifyURLs: false,
      noNewlinesBeforeTagClose: false,
      preserveLineBreaks: false,
      preventAttributesEscaping: false,
      processConditionalComments: false,
      removeAttributeQuotes: false,
      removeComments: true,
      removeEmptyAttributes: true,
      removeEmptyElements: false,
      removeOptionalTags: false,
      removeRedundantAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      removeTagWhitespace: false,
      sortAttributes: false,
      sortClassNames: false,
      useShortDoctype: true,
    }),
    compress({
      HTML: false,
      CSS: {
        csso: false,
        lightningcss: lightningCssOptions,
      },
      Exclude: ['88x31.svg'],
    }),
    generateCloudflareRoutes,
  ],
})
