import * as fs from 'node:fs'
import cloudflare from '@astrojs/cloudflare'
import type { AstroIntegration } from 'astro'
import { defineConfig } from 'astro/config'
import compress from 'astro-compress'
import htmlMinifierNext from 'astro-html-minifier-next'
import browserslist from 'browserslist'
import { browserslistToTargets } from 'lightningcss'

const lightningCssOptions = {
  minify: true,
  errorRecovery: false,
  targets: browserslistToTargets(browserslist('defaults')),
}

const locales: ['en', 'ja'] = ['en', 'ja']

const generateCloudflareRoutes: AstroIntegration = {
  name: 'generate-cloudflare-routes',
  hooks: {
    'astro:build:done': (result) => {
      const noLocalePages: Set<string> = new Set()
      for (const page of result.pages) {
        for (const locale of locales) {
          if (page.pathname.startsWith(locale)) {
            const pageUrl = page.pathname.slice(locale.length)
            noLocalePages.add(pageUrl)
          }
        }
      }

      const runWorkerFirst = [...noLocalePages]

      const wranglerJsonPath = new URL('../server/wrangler.json', result.dir)
      const existingWranglerText = fs.readFileSync(wranglerJsonPath).toString()
      const existingWrangler = JSON.parse(existingWranglerText)
      // biome-ignore lint/complexity/useLiteralKeys: it's not camelCase lol
      existingWrangler.assets['run_worker_first'] = runWorkerFirst
      const newWrangler = JSON.stringify(existingWrangler)
      fs.writeFileSync(wranglerJsonPath, newWrangler)
    },
  },
}

// https://astro.build/config
export default defineConfig({
  adapter: cloudflare({
    // we handle this with compress()
    imageService: 'passthrough',
    prerenderEnvironment: 'node',
  }),

  i18n: {
    locales,
    defaultLocale: 'en',
    routing: 'manual',
  },

  site: 'https://aly.fish',

  compressHTML: false,
  vite: {
    build: {
      cssMinify: 'lightningcss',
    },
    css: {
      lightningcss: lightningCssOptions,
    },
  },
  integrations: [
    htmlMinifierNext({
      alwaysWriteMinifiedHTML: true,
      caseSensitive: true,
      collapseBooleanAttributes: true,
      collapseInlineTagWhitespace: false,
      collapseWhitespace: true,
      conservativeCollapse: false,
      continueOnParseError: false,
      decodeEntities: true,
      includeAutoGeneratedTags: true,
      keepClosingSlash: false,
      minifyCSS: lightningCssOptions,
      minifyJS: true,
      minifyURLs: false,
      noNewlinesBeforeTagClose: false,
      preserveLineBreaks: false,
      preventAttributesEscaping: false,
      processConditionalComments: false,
      removeAttributeQuotes: false,
      removeComments: true,
      removeEmptyAttributes: true,
      removeEmptyElements: false,
      removeOptionalTags: false,
      removeRedundantAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      removeTagWhitespace: false,
      sortAttributes: false,
      sortClassNames: false,
      useShortDoctype: true,
    }),
    compress({
      HTML: false,
      CSS: {
        csso: false,
        lightningcss: lightningCssOptions,
      },
      Exclude: ['88x31.svg'],
    }),
    generateCloudflareRoutes,
  ],
})
