allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
overrides:
  "astro-compress>astro": "$astro"
  "astro-html-minifier-next>astro": "$astro"
  "@astrojs/cloudflare>astro": "$astro"
  "@astrojs/cloudflare>vite": "$vite"
