allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
catalog:
  astro: ^7.2.2
publicHoistPattern:
  - "sharp"
overrides:
  "astro-html-minifier-next>astro": "catalog:"
  "@emnapi/core": "^2.0.0-alpha.3"
  "@emnapi/runtime": "^2.0.0-alpha.3"
minimumReleaseAgeExclude:
  - miniflare@5.20260801.0-alpha
  - wrangler@4.119.0
